---
- name: Install Python pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true

- name: Copy Python requirements to monitoring node
  ansible.builtin.copy:
    src: "{{ requirements_file }}"
    dest: "{{ requirements_remote_file }}"
    owner: root
    group: root
    mode: "0644"

- name: Install monitoring node Python requirements
  ansible.builtin.pip:
    requirements: "{{ requirements_remote_file }}"
    executable: "{{ requirements_pip_executable }}"
